export const products = [
  {
    id: "Am2qmmLHI8l6zry6u7bh",
    productName: "MP Soap Pro",
    category: "Body Care",
    sellingCost: 120,
    manufacturingCost: 35,
    imageUrl:
      "https://res.cloudinary.com/dua8sce9b/image/upload/v1714412328/Introducing_Neem-Tulasi_Your_Ultimate_Solution_to_Dandruff_Woes_ziepkv.svg",
    description:
      "The MP Soap Pro is a premium soap bar designed to cleanse and nourish your skin. Crafted with high-quality ingredients, this soap provides a luxurious lather that effectively removes dirt and impurities without stripping away essential moisture. Perfect for daily use, it leaves your skin feeling refreshed and revitalized.",
  },
  {
    id: "DQt8gF1OQfsHkKmkFxob",
    category: "Body Care",
    manufacturingCost: 131,
    productName: "Bodywash Pro",
    sellingCost: 349,
    description:
      "Indulge in a spa-like experience with our Bodywash Pro. Formulated with gentle yet effective cleansing agents, this body wash deeply cleanses your skin while maintaining its natural moisture balance. Enriched with nourishing ingredients, it leaves your skin feeling soft, smooth, and rejuvenated after every shower.        ",
  },
  {
    id: "GxoQhnQIxMjUEKI2qlkl",
    productName: "Face gel Pro",
    sellingCost: 249,
    category: "Skin Care",
    manufacturingCost: 50,
    description:
      "Say goodbye to dull and tired-looking skin with our Face Gel Pro. This lightweight gel formula is packed with potent antioxidants and hydrating agents to refresh and revitalize your complexion. It absorbs quickly into the skin, delivering a boost of moisture and leaving your skin feeling energized and radiant.    ",
  },
  {
    id: "Jw2ocaMutG32FV5xeFQw",
    productName: "Shampoo ",
    sellingCost: 299,
    manufacturingCost: 120,
    category: "Hair Care",
    description:
      "Transform your hair care routine with our luxurious Shampoo. Infused with nourishing ingredients, this shampoo gently cleanses your hair and scalp while replenishing essential nutrients. It lathers into a rich foam, effectively removing dirt, oil, and product buildup without stripping away moisture. Say hello to soft, shiny, and healthy-looking hair with every wash.    ",
  },
  {
    id: "K9olkH1j3n7hTBGqVHT8",
    manufacturingCost: 70,
    category: "Skin Care",
    productName: "Face pack",
    sellingCost: 149,
  },
  {
    id: "KNt3iJJCXGhZuffF9tBv",
    sellingCost: 349,
    productName: "Face gel Pro Max",
    category: "Skin Care",
    manufacturingCost: 70,
  },
  {
    id: "Kf8XBaLRiQ8Brk5DAalv",
    category: "Body Care",
    productName: "Bath Powder",
    manufacturingCost: 30,
    sellingCost: 45,
  },
  {
    id: "LFzQ9qly60Kp8d1Pvfsy",
    sellingCost: 169,
    category: "Under eye Care",
    productName: "Undereye Gel",
    manufacturingCost: 30,
  },
  {
    id: "Wr2fMpakkAUUJN2COV9y",
    sellingCost: 299,
    category: "Skin Care",
    manufacturingCost: 131,
    productName: "Facewash",
  },
  {
    id: "aYMrfnJqHk7YITh4efyS",
    sellingCost: 149,
    productName: "Baldness Night oil",
    manufacturingCost: 70,
    category: "Hair Care",
  },
  {
    id: "dgRP3vMFTlgNU6R2unhf",
    manufacturingCost: 131,
    sellingCost: 299,
    category: "Body Care",
    productName: "Bodywash",
  },
  {
    id: "idt1bLaDLFtRn70MI78a",
    sellingCost: 349,
    productName: "Shampoo Pro",
    category: "Hair Care",
    manufacturingCost: 120,
  },
  {
    id: "nue2XPpuxh2C1IMKBCW6",
    sellingCost: 75,
    manufacturingCost: 30,
    productName: "MP Soap",
    category: "Body Care",
  },
  {
    id: "rUu70lYbdUruzotvrDe4",
    productName: "Face gel",
    sellingCost: 199,
    manufacturingCost: 40,
    category: "Skin Care",
  },
  {
    id: "svBdOYVKlRY1ERNVeuC0",
    sellingCost: 349,
    category: "Skin Care",
    productName: "Facewash Pro",
    manufacturingCost: 131,
  },
  {
    id: "tl8V2LMVIAEqkI0OwYs7",
    productName: "Kumkumadhi oil",
    category: "Skin Care",
    sellingCost: 399,
    manufacturingCost: 150,
  },
  {
    id: "uoAVs5p28OER9zdcmvfJ",
    category: "Hair Care",
    manufacturingCost: 70,
    productName: "Hair Pack",
    sellingCost: 149,
  },
];
